#pragma config(Sensor, dgtl2,  TurntableEndOfTravel, sensorTouch)
#pragma config(Sensor, dgtl3,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  startButton,    sensorTouch)
#pragma config(Sensor, dgtl11, creamerOut,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, coffeeOut,      sensorLEDtoVCC)
#pragma config(Motor,  port1,           turnTable,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           sugarServo,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "headers/moveTable.h"	//Include the moveTable header
//#include "headers/ce2libraries/init.h"	//Include the startup header
#include "headers/ce2libraries/blink.h"	//Include the blink header

//Consts
int requestedSugar = 2; //the number of sugar tumbles to add

//Jobs
bool cupJobDone = true;	//Init job as done
bool sugarJobDone = true;	//Init job as done
bool creamerJobDone = true;	//Init job as done
bool coffeeJobDone = true;	//Init job as done
#include "jobs.c" //Include all of the jobs

task main()
{
	while(true)
	{
		//startup(enableBot,LED);	//Wait till the startup button enableBot Is pressed
		//Get inital values for production

		moveTable(1);	//Move one space
		startAllTasks();	//Start all of the tasks

		while ((cupJobDone == false) || (sugarJobDone == false) || (creamerJobDone == false) || (coffeeJobDone == false))	//Wait for every task to tell us that it is complete
		{
			blink(LED, 3);	//Tripple blink the LED
		}
	}
}
