#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  TurntableEndOfTravel, sensorTouch)
#pragma config(Motor,  port1,           turnTable,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "headers/moveTable.h"

task main()
{
	while(true)
	{
		moveTable(1); //Move one space
		delay(2000); //wait
		moveTable(2); //Move two spaces
		delay(2000); //wait
	}
}
