#pragma config(Sensor, dgtl3,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, creamerOut,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, coffeeOut,      sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		sensorvalue(coffeeOut)=true;
		delay(1000);
		sensorvalue(creamerOut)=false;
		sensorvalue(LED)=true;
		delay(400);
		sensorvalue(coffeeOut)=false;
		delay(120);
		sensorvalue(creamerOut)=true;
		sensorvalue(LED)=false;
		delay(1000);
	}
}
