#pragma config(Sensor, dgtl3,  LED,            sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


bool taskIsDone = false;
int i = 1000;

task myTask()
{
	while(i > 0)
	{
		delay(5);
		i--;
	}
	taskIsDone = true;
	stopTask(myTask);
}

task main()
{
	startTask(myTask);

	while(taskIsDone == false)
	{
		delay(50);
	}

	while(true)
	{
		SensorValue[LED] = true;
		delay(800);
		SensorValue[LED] = false;
		delay(800);
	}
}
